language: node_js
node_js:
  - '10'

install:
  - npm install
  - npm run build

script:
  - npm run test_with_report

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release